# Use official Ubuntu 24.04 as the base image
# docker build -f ./Dockerfile.old_ansible_and_python -t ansible-automation ../..
# This setup is compatible if the remote machine has old python like 2.7.x, 3.6.x, 3.9.x etc.
FROM ubuntu:24.04

# Set environment variable to prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Define versions for dependencies
ENV PYTHON_VERSION=3.10
ENV PYWINRM_VERSION=0.5.0
ENV ANSIBLE_MAX_VERSION=2.14
ENV PYTHON_PIP_VERSION=25.0.1

RUN apt-get update && apt-get install -y --no-install-recommends \
        sshpass \
        openssh-client \
        git \
        tzdata \
        software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Set timezone
RUN ln -fs /usr/share/zoneinfo/Australia/Sydney /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Create a virtual environment
RUN python${PYTHON_VERSION} -m venv /opt/venv

# Ensure the virtual environment is automatically used in all shell sessions
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip and install Ansible (compatible with remote Python like 2.7.x, 3.6.x, 3.9.x etc.)
RUN python -m pip install --upgrade pip==${PYTHON_PIP_VERSION} && \
    pip install --index-url https://pypi.org/simple "ansible-core<${ANSIBLE_MAX_VERSION}" \
    pywinrm==${PYWINRM_VERSION}

# Verify the installed Ansible version
RUN ansible --version

# Reset DEBIAN_FRONTEND to its default
ENV DEBIAN_FRONTEND=

# Set the working directory
WORKDIR /ansible

COPY docker/ansible_host/scripts/install_cert.sh /usr/local/bin/install_cert.sh

# Make sure the script is executable
RUN chmod +x /usr/local/bin/install_cert.sh

# Set the default command to keep the container running
CMD [ \
    "/bin/sh", "-c", \
    "python3 --version && \
    pip --version && \
    pip show pywinrm && \
    ansible --version && \
    ansible-playbook --version && \
    tail -f /dev/null" \
]