services:
  ansible:
    # To rebuild the image, run either of the two:
    # DOCKERFILE=Dockerfile.old_ansible_and_python docker-compose up --build
    # docker compose up --build
    # docker build -f ./Dockerfile -t ansible-automation ../..
    build:
      context: ../..
      dockerfile: docker/ansible_host/${DOCKERFILE:-Dockerfile}
#      dockerfile: docker/ansible_host/Dockerfile
#      dockerfile: docker/ansible_host/Dockerfile.old_ansible_and_python
    container_name: ansible
    image: ansible-automation:latest
    volumes:
      - ../../ansible:/ansible
      - ../../ansible/ansible.cfg:/etc/ansible/ansible.cfg:ro
      - ../../certs/${ENVIRONMENT}/:/certs:ro
      # If the following dir is missing, then start the vault_agent first to create the secrets dir contents
      - ../vault_agent/secrets/agent/ssh_keys/ansible:/root/.ssh
      - ../vault_agent/secrets/agent/ssh_keys/${ENVIRONMENT}/linux_explicit_ssh_keys_host/id_rsa.pub:/root/.ssh/linux_explicit_ssh_keys_host.pub
      - ./scripts:/usr/local/bin
    env_file:
      - .env
    environment:
      - RESET_HOSTS_FILE=false
      - RUN_TESTS=${RUN_TESTS:-false}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - COMPOSE_PROFILES=${COMPOSE_PROFILES:-default}
      # As the certs directory is not committed to Git, so to set RUN_WITH_CERTIFICATE to true,
      # we first need to create a script to generate certs on linux machine, i.e. in ansible container.
      - RUN_WITH_CERTIFICATE=${RUN_WITH_CERTIFICATE}
    extra_hosts:
      - local_windows_vm:host-gateway # The host-gateway keyword resolves to the host's IP address on the bridge network.
    network_mode: host
    stdin_open: true
    tty: true
