services:
  vault_agent:
    build:
      context: ../..
      dockerfile: docker/vault_agent/Dockerfile
    image: custom_vault_agent:latest
    container_name: vault_agent
    cap_add:
      - IPC_LOCK  # Allow Vault to lock memory for production-like setups
    env_file:
      - .env
    environment:
      SKIP_SETCAP: false
    networks:
      - ansible_network
    volumes:
      - vault_file:/vault/file
      - vault_logs:/vault/logs
      - ./scripts:/vault/scripts
      - ./secrets:${SECRETS_DIR}
      - ./config:/vault/config:ro
      # If the following dir/volume is missing, then start the vault_server first to create the auth dir contents
      - vault_ssh_manager_role:${VAULT_SERVER_ROLE_AUTH_DIR}:ro
    entrypoint: [ "sh", "/vault/scripts/agent_startup.sh" ]
    # TODO: Run the service with vault user instead of the root user
    # 100:1000 is the UID:GID of the vault user in the container.
    # user: "100:1000"  # Ensure container runs as 'vault' user
    healthcheck:
      test:
        [
          "CMD", "sh", "-c",
          "pgrep -f 'vault agent' > /dev/null && \
           test -s ${VAULT_ANSIBLE_SSH_KEYS_DIR}/id_rsa.pub && \
           ! grep -q '^[[:space:]]*$' ${VAULT_ANSIBLE_SSH_KEYS_DIR}/id_rsa.pub || exit 1"
        ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

volumes:
  vault_file:
  vault_logs:
  vault_ssh_manager_role:

networks:
  ansible_network:
    driver: bridge
