services:
  hashicorp_vault:
    image: hashicorp/vault:1.18.3
    container_name: hashicorp_vault
    ports:
      - "127.0.0.1:8200:8200" # Restrict port mapping to localhost
    volumes:
      - vault_file:/vault/file
      - vault_logs:/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    networks:
      - ansible_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo -e 'GET /v1/sys/health HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n' | nc -w 5 127.0.0.1 8200 | grep '200 OK'"
        ]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 10s

volumes:
  vault_file:
  vault_logs:

networks:
  ansible_network:
    driver: bridge