services:
  hashicorp_vault:
    build:
      context: ../..
      dockerfile: docker/hashicorp_vault/Dockerfile
    image: custom_vault:latest
    container_name: hashicorp_vault
    ports:
      - "127.0.0.1:8200:8200" # Restrict port mapping to localhost
    cap_add:
      - IPC_LOCK  # Allow Vault to lock memory for production-like setups
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SERVER_MODE: ${SERVER_MODE:-prod}
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - raft_data:/vault/raft
      - vault_file:/vault/file
      - vault_logs:/vault/logs
      - ./scripts:/vault/scripts
      - ./unseal_keys:/vault/keys
      - ./policies:/vault/policies:ro
      - ./config/vault_config.hcl:/vault/config/vault_config.hcl:ro
    entrypoint: [ "sh", "/vault/scripts/vault_startup.sh" ]
    networks:
      - ansible_network
    healthcheck:
      test:
        [
          "CMD", "sh", "-c",
          "printf 'GET /v1/sys/health HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc -w 5 127.0.0.1 8200 | grep -E '200 OK|initialized'"
        ]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 10s

volumes:
  raft_data:
  vault_file:
  vault_logs:

networks:
  ansible_network:
    driver: bridge