services:
  ansible:
    build:
      context: .
    container_name: ansible
    image: ansible-automation:latest
    volumes:
      - ./ansible:/ansible
    env_file:
      - .env
    network_mode: "host" # Use host network for SSH
    stdin_open: true
    tty: true
    entrypoint: >
      sh -c "
        ansible -i ansible-playbook /ansible/playbook.yml -i /ansible/inventory.yml;
        tail -f /dev/null
      "
