---

docker_edition: "ce"
docker_version: "28.0.4"
docker_packages:
  - "docker-{{ docker_edition }}-{{ docker_version }}"
  - "docker-{{ docker_edition }}-cli-{{ docker_version }}"
  - "docker-{{ docker_edition }}-rootless-extras-{{ docker_version }}"
docker_packages_state: present

docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_compose_version: "2.34.0"
docker_install_compose_plugin: true
docker_compose_package_state: present
docker_compose_package: "docker-compose-plugin-{{ docker_compose_version }}"

docker_users:
  - jenkins
docker_daemon_options:
  # If the docker daemon fails to start due to the unsupported storage driver, you can skip setting it
  storage-driver: "{{ docker_storage_driver }}"
  log-opts:
    # Keep up to 5 log files, each max 50MB → so worst-case logs use ~250MB per container.
    max-file: "5"
    max-size: "50m"
