all:

  children:
    # Add ansible/inventory/${ENVIRONMENT}/group_vars/metricbeat_hosts.yml to define required variables
    # NOTE: the yml file name should be same as the inventory group name
    metricbeat_hosts:
      hosts:
        # IP can also be used instead of the hostname
        oau-tf-prod-web1:
          ansible_host: 192.168.173.20
        oau-tf-prod-web2:
          ansible_host: 192.168.173.21
        oau-tf-prod-app1:
          ansible_host: 192.168.173.22
        oau-tf-prod-app2:
          ansible_host: 192.168.173.23
        oau-tf-prod-db1:
          ansible_host: 192.168.173.24
          ansible_python_interpreter: /usr/bin/python
        oau-tf-prod-db2:
          ansible_host: 192.168.173.25
          ansible_python_interpreter: /usr/bin/python
        oau-tf-prod-service1:
          ansible_host: 192.168.173.26
        oau-tf-prod-service2:
          ansible_host: 192.168.173.27
        oau-tf-prod-service3:
          ansible_host: 192.168.173.28
        oau-tf-prod-lb1:
          ansible_host: 192.168.173.29
        oau-tf-prod-lb2:
          ansible_host: 192.168.173.30
        oau-tf-prod-witness:
          ansible_host: 202.93.102.146
