---
- name: Gather OS Facts
  setup:
  become: true

- name: Determine if OS is legacy
  set_fact:
    legacy_os: "{{ ansible_distribution_major_version | int < os_legacy_threshold }}"

- name: Set Metricbeat version based on OS version
  set_fact:
    metricbeat_version: "{{ metricbeat_version_legacy if legacy_os else metricbeat_version_modern }}"

- name: Import Elastic GPG key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
  become: true

- name: Add Elastic repository
  yum_repository:
    name: "elastic-{{ metricbeat_version }}"
    description: "Elastic repository for {{ metricbeat_version }} packages"
    baseurl: "https://artifacts.elastic.co/packages/{{ metricbeat_version }}/yum"
    gpgcheck: yes
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    enabled: yes
  become: true

- name: Install Metricbeat
  yum:
    name: metricbeat
    state: present
  become: true

- name: Backup the existing Metricbeat configuration
  copy:
    src: "{{ METRICBEAT_YML_PATH }}"
    dest: "{{ METRICBEAT_YML_PATH }}.old"
    remote_src: yes
    mode: preserve
  become: true

- name: Update Metricbeat configuration (customized config)
  template:
    src: metricbeat.yml.j2
    dest: "{{ METRICBEAT_YML_PATH }}"
    mode: '0644'
  notify: Restart Metricbeat
  become: true

- name: Flush handlers to restart Metricbeat immediately if config changed
  meta: flush_handlers
