---
- name: Gather OS Facts
  ansible.builtin.setup:
  become: true

- name: Determine if OS is legacy
  ansible.builtin.set_fact:
    legacy_os: "{{ ansible_distribution_major_version | int < metricbeat_os_legacy_threshold }}"

- name: Set Metricbeat version based on OS version
  ansible.builtin.set_fact:
    metricbeat_version: "{{ metricbeat_version_legacy if legacy_os else metricbeat_version_modern }}"

- name: Import Elastic GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: true

- name: Add Elastic repository
  ansible.builtin.yum_repository:
    name: "elastic-{{ metricbeat_version }}"
    description: "Elastic repository for {{ metricbeat_version }} packages"
    baseurl: "https://artifacts.elastic.co/packages/{{ metricbeat_version }}/yum"
    gpgcheck: true
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    enabled: true
  become: true

- name: Install Metricbeat
  # 'noqa fqcn' tells ansible-lint to skip the FQCN check for this line.
  ansible.builtin.yum: # noqa fqcn
    name: metricbeat
    state: present
  become: true

- name: Backup the existing Metricbeat configuration
  ansible.builtin.copy:
    src: "{{ metricbeat_yml_path }}"
    dest: "{{ metricbeat_yml_path }}.old"
    remote_src: true
    mode: preserve
  become: true

- name: Update Metricbeat configuration (customized config)
  ansible.builtin.template:
    src: metricbeat.yml.j2
    dest: "{{ metricbeat_yml_path }}"
    mode: '0644'
  notify: Restart Metricbeat
  become: true

- name: Flush handlers to restart Metricbeat immediately if config changed
  ansible.builtin.meta: flush_handlers

- name: Verify Metricbeat connection to Elasticsearch
  ansible.builtin.command: metricbeat test output
  register: metricbeat_test_output
  failed_when: false
  changed_when: false
  become: true

- name: Fail if Metricbeat connection test fails
  ansible.builtin.fail:
    msg: |
      Metricbeat failed to connect to Elasticsearch!
      - Check Metricbeat logs and ensure the service is running.
      - Verify that the configuration in metricbeat.yml is correct.
      - Run manually: metricbeat test output
      - If it's an authentication issue, check the credentials for user [{{ metricbeat_elasticsearch_username }}].
      - For further debugging, try: curl -u {{ metricbeat_elasticsearch_username }}:'your_password'
        -X GET {{ metricbeat_elasticsearch_protocol }}://{{ metricbeat_elasticsearch_host }}
  when: "'error' in metricbeat_test_output.stdout or 'FAIL' in metricbeat_test_output.stdout"
