services:
  ansible:
    # To rebuild the image, run either of the two:
    # docker-compose up --build
    # docker build -f ./Dockerfile.ansible -t ansible-automation ..
    build:
      context: ..
      dockerfile: docker/Dockerfile.ansible
    container_name: ansible
    image: ansible-automation:latest
    volumes:
      - ../ansible:/ansible:ro
      - ../ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ../.ssh_keys/${ENVIRONMENT}:/root/.ssh
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-local}
    extra_hosts:
      - local_windows_vm:host-gateway # The host-gateway keyword resolves to the host's IP address on the bridge network.
    networks:
      - ansible_network
    stdin_open: true
    tty: true
    entrypoint: >
      sh -c '
        # Remove any existing known hosts entry for linux_ssh_pass_host to avoid key mismatch
        if [ -f /root/.ssh/known_hosts ]; then
          ssh-keygen -f /root/.ssh/known_hosts -R "linux_ssh_pass_host"
        fi

        # Ensure proper permissions for the .ssh directory and private key
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/id_rsa
        chown root:root /root/.ssh/id_rsa

        # Run the Ansible playbooks
        if [ "${COMPOSE_PROFILES}" = "CI" ]; then
          echo "CI profile detected. Running Windows playbook only."
          ansible-playbook \
            -i /ansible/inventory/${ENVIRONMENT}/hosts.yml \
            /ansible/playbooks/deploy_windows.yml \
            -e ENVIRONMENT=${ENVIRONMENT}
        else
          echo "Non-CI profile detected. Running both Linux and Windows playbooks."
          ansible-playbook \
            -i /ansible/inventory/${ENVIRONMENT}/hosts.yml \
            /ansible/playbooks/deploy_linux.yml \
            /ansible/playbooks/deploy_windows.yml \
            -e ENVIRONMENT=${ENVIRONMENT}
        fi

        # Keep the container running (necessary for Docker to keep the container alive)
        tail -f /dev/null
      '
    depends_on:
      linux_ssh_pass_host:
        condition: service_healthy
      linux_ssh_keys_host:
        condition: service_healthy
    profiles: ["default"]

  linux_ssh_pass_host:
    # To rebuild the image, run either of the two:
    # docker-compose up --build
    # docker build -f ./Dockerfile.linuxSshPassHost -t linux_ssh_pass_host ..
    build:
      context: ..
      dockerfile: docker/Dockerfile.linuxSshPassHost
    container_name: linux_ssh_pass_host
    image: linux_ssh_pass_host:latest
    tty: true
    stdin_open: true
    networks:
      - ansible_network
    healthcheck:
      test: [ "CMD", "sshd", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["default"]

  linux_ssh_keys_host:
    # To rebuild the image, run either of the two:
    # docker-compose up --build
    # docker build -f ./Dockerfile.linuxSshKeysHost -t linux_ssh_keys_host ..
    build:
      context: ..
      dockerfile: docker/Dockerfile.linuxSshKeysHost
    container_name: linux_ssh_keys_host
    image: linux_ssh_keys_host:latest
    volumes:
      - ../.ssh_keys/${ENVIRONMENT}/id_rsa.pub:/root/.ssh/authorized_keys
    tty: true
    stdin_open: true
    networks:
      - ansible_network
    healthcheck:
      test: [ "CMD", "sshd", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["default"]

networks:
  ansible_network:
    driver: bridge
