services:
  ansible:
    extends:
      file: ./ansible_host/docker-compose.yml
      service: ansible
    env_file:
      - .env
    network_mode: "" # Reset network_mode
    networks:
      - ansible_network
    depends_on:
      linux_ssh_pass_host:
        condition: service_healthy
      linux_ssh_keys_host:
        condition: service_healthy
    profiles: ["default", "test"]

  linux_ssh_pass_host:
    extends:
      file: ./linux_ssh_pass_host/docker-compose.yml
      service: linux_ssh_pass_host
    profiles: ["default", "test"]

  linux_ssh_keys_host:
    extends:
      file: ./linux_ssh_keys_host/docker-compose.yml
      service: linux_ssh_keys_host
    profiles: ["default", "test"]

networks:
  ansible_network:
    driver: bridge
