services:
  ansible:
    # To rebuild the image, run either of the two:
    # docker-compose up --build
    # docker build -f ./Dockerfile -t ansible-automation ..
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ansible
    image: ansible-automation:latest
    volumes:
      - ../ansible:/ansible
      - ../ansible/ansible.cfg:/etc/ansible/ansible.cfg
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-local}
    network_mode: "host" # Use host network for SSH
    stdin_open: true
    tty: true
    entrypoint: >
      sh -c "
        ansible -i /ansible/inventory/${ENVIRONMENT}/hosts.yml /ansible/playbooks/deploy_windows.yml -e ENVIRONMENT=${ENVIRONMENT};
        tail -f /dev/null
      "
