services:
  # Run it with: COMPOSE_PROFILES=CI docker compose -f docker-compose.yml -f docker-compose-ci.override.yml up
  ansible:
    network_mode: host
    networks: !reset []
    depends_on: !reset []
    profiles: ["CI"]