# Use Ubuntu 22.04 as the base image
# docker build -f ./Dockerfile.linuxhost -t linux_host ..
FROM ubuntu:22.04

# Install SSH server and clean up package manager cache
RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo "root:rootpassword" | chpasswd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose SSH port
EXPOSE 22

# Start SSH service by default
CMD ["/usr/sbin/sshd", "-D"]