services:
  vault_server:
    extends:
      file: ./vault_server/docker-compose.yml
      service: vault_server
    profiles: ["default", "test"]

  vault_agent:
    extends:
      file: ./vault_agent/docker-compose.yml
      service: vault_agent
    depends_on:
      vault_server:
        condition: service_healthy
    profiles: ["default", "test"]

  ansible:
    extends:
      file: ./ansible_host/docker-compose.yml
      service: ansible
    env_file:
      - .env
    environment:
      - RESET_HOSTS_FILE=true
    network_mode: "" # Reset network_mode
    networks:
      - ansible_network
    depends_on:
      vault_agent:
        condition: service_healthy
      linux_ssh_pass_host:
        condition: service_healthy
      linux_ssh_keys_host:
        condition: service_healthy
    profiles: ["default", "test"]

  linux_ssh_pass_host:
    extends:
      file: ./linux_ssh_pass_host/docker-compose.yml
      service: linux_ssh_pass_host
    profiles: ["default", "test"]

  linux_ssh_keys_host:
    extends:
      file: ./linux_ssh_keys_host/docker-compose.yml
      service: linux_ssh_keys_host
    depends_on:
      vault_agent:
        condition: service_healthy
    profiles: ["default", "test"]

volumes:
  raft_data:
  vault_file:
  vault_logs:

networks:
  ansible_network:
    driver: bridge
