- name: Extract Tomcat version from filename
  ansible.builtin.set_fact:
    extracted_version: "{{ upgrade_tomcat_zip_filename | regex_search('(\\d+(\\.\\d+)+)') | replace('.', '_') }}"

- name: Construct the version-specific Upgraded Service Name
  ansible.builtin.set_fact:
    upgrade_tomcat_upgraded_service_name: "TOMCAT_{{ extracted_version }}_SRVA"
