- name: Prepare Tomcat upgrade
  ansible.builtin.include_tasks: prepare_tomcat_upgrade.yml
  when: upgrade_tomcat_upgrade_step == "prepare"

- name: Perform Tomcat upgrade
  ansible.builtin.include_tasks: tomcat_upgrade_tasks.yml
  vars:
    log_file_postfix: upgrade
    powershell_script_runner_file: upgrade_script_runner.yml
  when: upgrade_tomcat_upgrade_step == "upgrade"
