---
- name: Gather OS Facts
  ansible.builtin.setup:
  become: true

- name: Find matching APM agent JAR files
  ansible.windows.win_find:
    paths: "{{ upgrade_tomcat_tomcat_installation_drive }}\\tomcat\\srva\\lib\\elastic"
    patterns: elastic-apm-agent-*.jar
  register: found_files

- name: Fail if there is more than one matching file
  ansible.builtin.fail:
    msg: >-
      Multiple elastic-apm-agent-*.jar files found:
      {{ found_files.files | map(attribute='path') | list }}.
      Please delete the ones that are not required and keep only one.
  when: found_files.matched | int > 1

- name: Delete destination directory if exists
  ansible.windows.win_file:
    path: "{{ upgrade_tomcat_utility_destination_path }}"
    state: absent

- name: Copy scripts
  ansible.windows.win_copy:
    src: "{{ upgrade_tomcat_utility_scripts_path }}/"
    dest: "{{ upgrade_tomcat_utility_destination_path }}\\"

- name: Copy Tomcat ZIP
  ansible.windows.win_copy:
    src: "{{ upgrade_tomcat_utility_downloads_path }}/{{ upgrade_tomcat_zip_filename }}"
    dest: "{{ upgrade_tomcat_utility_destination_path }}\\"

- name: Include tasks to construct the Tomcat service name
  ansible.builtin.include_tasks: construct_service_name.yml

- name: Ensure logs directory exists
  ansible.windows.win_file:
    path: "{{ upgrade_tomcat_utility_destination_path }}\\logs"
    state: directory

- name: Define log file path
  ansible.builtin.set_fact:
    upgrade_tomcat_utility_log_path: "{{ upgrade_tomcat_utility_destination_path }}\\logs\\{{ ansible_hostname }}_prep.log"

- name: Run the PowerShell script and log output
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File "prepare_tomcat_upgrade.ps1" `
      -upgradedServiceName "{{ upgraded_service_name }}" `
      -tomcatZipPath "{{ upgrade_tomcat_zip_filename }}" `
      -tomcatInstallationDrive "{{ upgrade_tomcat_tomcat_installation_drive }}" `
      *> "{{ upgrade_tomcat_utility_log_path }}" 2>&1
  args:
    chdir: "{{ upgrade_tomcat_utility_destination_path }}"

- name: Include tasks to check the logs
  ansible.builtin.include_tasks: check_logs.yml
