---
- name: Find matching APM agent JAR files
  ansible.windows.win_find:
    paths: "{{ upgrade_tomcat_tomcat_installation_drive }}\\tomcat\\srva\\lib\\elastic"
    patterns: elastic-apm-agent-*.jar
  register: found_files

- name: Fail if there is more than one matching file
  ansible.builtin.fail:
    msg: >-
      Multiple elastic-apm-agent-*.jar files found:
      {{ found_files.files | map(attribute='path') | list }}.
      Please delete the ones that are not required and keep only one.
  when: found_files.matched | int > 1

- name: Delete destination directory if exists
  ansible.windows.win_file:
    path: "{{ upgrade_tomcat_utility_destination_path }}"
    state: absent

- name: Copy scripts
  ansible.windows.win_copy:
    src: "{{ upgrade_tomcat_utility_scripts_path }}/"
    dest: "{{ upgrade_tomcat_utility_destination_path }}\\"

- name: Copy Tomcat ZIP
  ansible.windows.win_copy:
    src: "{{ upgrade_tomcat_utility_downloads_path }}/{{ upgrade_tomcat_zip_filename }}"
    dest: "{{ upgrade_tomcat_utility_destination_path }}\\"

- name: Perform Tomcat upgrade preparation
  ansible.builtin.include_tasks: tomcat_upgrade_tasks.yml
  vars:
    log_file_postfix: prep
    powershell_script_runner_file: prep_script_runner.yml
