---
- name: Run the PowerShell script and log output
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'scripts/prepare_tomcat_upgrade.ps1') }}"
    parameters:
      upgradedServiceName: "{{ upgrade_tomcat_upgraded_service_name }}"
      tomcatZipPath: "{{ upgrade_tomcat_zip_filename }}"
      tomcatInstallationDrive: "{{ upgrade_tomcat_tomcat_installation_drive }}"
  args:
    chdir: "{{ upgrade_tomcat_utility_destination_path }}"
  register: ps_output
