---
- name: Gather OS Facts
  ansible.builtin.setup:

- name: Include tasks to construct the Tomcat service name
  ansible.builtin.include_tasks: construct_service_name.yml

- name: Ensure logs directory exists
  ansible.windows.win_file:
    path: "{{ upgrade_tomcat_utility_destination_path }}\\logs"
    state: directory

- name: Define log file path
  ansible.builtin.set_fact:
    upgrade_tomcat_utility_log_path: "{{ upgrade_tomcat_utility_destination_path }}\\logs\\{{ ansible_hostname }}_{{ log_file_postfix}}.log"

- name: Include task to run PowerShell script
  ansible.builtin.include_tasks: "{{ powershell_script_runner_file }}"

- name: Include tasks to check the logs
  ansible.builtin.include_tasks: save_and_analyze_logs.yml
