---
- name: Deploy to Linux host
  hosts: linux_hosts

  tasks:
    - name: Print available hosts
      ansible.builtin.debug:
        msg: "Available hosts: {{ ansible_play_hosts }}"

    - name: Debug hosts
      ansible.builtin.debug:
        var: inventory_hostname

    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: "{{ DESTINATION_PATH | dirname }}"
        state: directory
        mode: '0755'  # You can adjust the mode if needed

    - name: Copy a file to the remote linux machine
      ansible.builtin.copy:
        src: "{{ FILE_TO_COPY }}"
        dest: "{{ DESTINATION_PATH }}"
        mode: '0644'  # Adjust file permissions as needed

    - name: Ensure /tmp is writable for curl installation
      ansible.builtin.file:
        path: /tmp
        mode: "1777"
        state: directory
      become: true

    - name: Install curl
      ansible.builtin.apt:
        name: "curl"
        state: present
      become: true

    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello, Linux Host!"
