---
- name: Deploy to Windows host
  hosts: windows_hosts

  tasks:
    - name: Print available hosts
      ansible.builtin.debug:
        msg: "Available hosts: {{ ansible_play_hosts }}"

    - name: Debug hosts
      ansible.builtin.debug:
        var: inventory_hostname

    - name: Ensure the destination directory exists
      ansible.windows.win_file:
        path: "{{ DESTINATION_PATH | win_dirname }}"
        state: directory
        mode: '0755'  # Adjust file permissions as needed

    - name: Copy a file to the remote Windows machine
      ansible.windows.win_copy:
        src: "{{ FILE_TO_COPY }}"
        dest: "{{ DESTINATION_PATH }}"
        mode: '0644'  # Adjust file permissions as needed

    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello, Windows Host!"
