- name: Install Docker on Oracle Linux 9
  hosts: jenkins_hosts
  become: true

  tasks:
    - name: Ensure jenkins user exists
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash

    - name: Install Docker using geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_version: "28.0.4"
        docker_packages:
          - "docker-{{ docker_edition }}-{{ docker_version }}"
          - "docker-{{ docker_edition }}-cli-{{ docker_version }}"
          - "docker-{{ docker_edition }}-rootless-extras-{{ docker_version }}"
        docker_packages_state: present
        docker_service_manage: true
        docker_users:
          - jenkins
