all:

  children:

    tomcat_windows_hosts:
      hosts:
        oau-dev-01:
          ansible_host: 192.168.182.13
          upgrade_tomcat_tomcat_installation_drive: "D:"
          upgrade_tomcat_setup_log_on_creds: true
          upgrade_tomcat_log_on_username: "svc_octane_dev@octaneaudev.internal"
          upgrade_tomcat_log_on_password: "{{ vault_svc_octane_dev_password }}"
          upgrade_tomcat_jvm_dll_path: 'D:\java\jre8.0.412-x64zulu\bin\server\jvm.dll'
