all:
  hosts:
    localhost:
      ansible_connection: local

    local_windows: # working with valid certs
      ansible_port: 55986
      # You can either use `local_windows_vm` by defining `extra_hosts` in docker-compose.yml,
      # or use `host.docker.internal` to access host from within the container - Should work out of the box.
      ansible_host: local_windows_vm
      ansible_connection: winrm
      ansible_winrm_scheme: https
      ansible_user: ansible-agent
      ansible_password: ANS1BLE_P@sS!
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: validate
      ansible_winrm_ca_trust_path: /etc/ssl/certs/ca-certificates.crt

#    local_windows: # Working with no or invalid certs
#      ansible_port: 55986
#      # You can either use `local_windows_vm` by defining `extra_hosts` in docker-compose.yml,
#      # or use `host.docker.internal` to access host from within the container - Should work out of the box.
#      ansible_host: local_windows_vm
#      ansible_connection: winrm
#      ansible_winrm_scheme: https
#      ansible_user: ansible-agent
#      ansible_password: ANS1BLE_P@sS!
#      ansible_winrm_transport: basic
#      ansible_winrm_server_cert_validation: ignore
#
#    local_windows: # working settings
#      ansible_port: 55985
#      ansible_host: host.docker.internal # Just a way to access host from within the container
#      ansible_connection: winrm
#      ansible_winrm_scheme: http
#      ansible_user: ansible-agent
#      ansible_password: ANS1BLE_P@sS!
#      ansible_winrm_transport: basic

  children:
    linux_hosts:
      hosts:
        linux_ssh_pass_host:
          ansible_host: linux_ssh_pass_host
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_pass: rootpassword
          ansible_port: 22

        linux_ssh_keys_host:
          ansible_host: linux_ssh_keys_host
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
          ansible_port: 22
