all:

  children:
    localhost:
      hosts:
        localhost:
          ansible_connection: local

    windows_hosts:
      hosts:
        local_windows: # working with valid certs
          # You can either use `local_windows_vm` by defining `extra_hosts` in docker-compose.yml,
          # or use `host.docker.internal` to access host from within the container - Should work out of the box.
          ansible_host: local_windows_vm

    linux_hosts:
      hosts:
        linux_ssh_pass_host:
          ansible_host: linux_ssh_pass_host
          ansible_ssh_pass: rootpassword

        linux_implicit_ssh_keys_host:
          ansible_host: linux_implicit_ssh_keys_host
          ansible_ssh_private_key_file: /root/.ssh/id_rsa

        linux_explicit_ssh_keys_host:
          ansible_host: linux_explicit_ssh_keys_host
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
