all:
  hosts:
    localhost:
      ansible_connection: local

    local_windows:
      ansible_port: 55985
      ansible_host: local_windows_vm
      ansible_connection: winrm
      ansible_winrm_scheme: http
      ansible_user: ansible-agent
      ansible_password: ANS1BLE_P@sS!
      ansible_winrm_transport: plaintext
      ansible_winrm_client_basic_auth_only: true

  children:
    linux_hosts:
      hosts:
        linux_ssh_pass_host:
          ansible_host: linux_ssh_pass_host
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_pass: rootpassword
          ansible_port: 22

        linux_ssh_keys_host:
          ansible_host: linux_ssh_keys_host
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
          ansible_port: 22
