all:
  hosts:
    localhost:
      ansible_connection: local

    local_windows: # working with valid certs
      # You can either use `local_windows_vm` by defining `extra_hosts` in docker-compose.yml,
      # or use `host.docker.internal` to access host from within the container - Should work out of the box.
      ansible_host: local_windows_vm

  children:
    linux_hosts:
      hosts:
        linux_ssh_pass_host:
          ansible_host: linux_ssh_pass_host
          ansible_ssh_pass: rootpassword

        linux_ssh_keys_host:
          ansible_host: linux_ssh_keys_host
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
