services:
  linux_ssh_pass_host:
    # To rebuild the image, run either of the two:
    # docker compose up --build
    # docker build -f ./Dockerfile -t linux_ssh_pass_host .
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linux_ssh_pass_host
    image: linux_ssh_pass_host:latest
    tty: true
    stdin_open: true
    networks:
      - ansible_network
    healthcheck:
      test: [ "CMD", "sshd", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ansible_network:
    driver: bridge
