services:
  vault_server:
    image: hashicorp/vault:1.18.3
    container_name: vault_server
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK  # Allow Vault to lock memory for production-like setups
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SERVER_MODE: ${SERVER_MODE:-prod}
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "https://127.0.0.1:8200"
      VAULT_CACERT: /vault/certs/ca.crt
      ######## For mTLS start ##################
      VAULT_CLIENT_KEY: /vault/certs/agent.key
      VAULT_CLIENT_CERT: /vault/certs/agent.crt
      ######## For mTLS end ####################
      SSH_MANAGER_ROLE_NAME: ${SSH_MANAGER_ROLE_NAME:-ssh_manager_role}
    volumes:
      - raft_data:/vault/raft
      - vault_file:/vault/file
      - vault_logs:/vault/logs
      - ./secrets:/vault/secrets
      # NOTE: Run the scripts/generate_certificate.sh on the host first, to generate the cert
      - ./certs/vaultCA/intermediate/cacert.pem:/vault/certs/ca.crt:ro
      - ./certs/vaultCA/agent/server_crt.pem:/vault/certs/agent.crt:ro
      - ./certs/vaultCA/agent/server_key.pem:/vault/certs/agent.key:ro
      - ./certs/vaultCA/server/server_key.pem:/vault/certs/server.key:ro
      - ./certs/vaultCA/server/full_chain.pem:/vault/certs/full_chain.pem:ro
      - vault_ssh_manager_role:/vault/secrets/auth/${SSH_MANAGER_ROLE_NAME}
      - ./scripts:/vault/scripts
      - ./policies:/vault/policies:ro
      - ./config/vault_server.hcl:/vault/config/vault_server.hcl:ro
    entrypoint: [ "sh", "/vault/scripts/vault_startup.sh" ]
    networks:
      - ansible_network
    healthcheck:
      test:
        [
          "CMD", "sh", "-c",
          "vault status | grep -E 'Sealed\\s*false'"
        ]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 10s

volumes:
  raft_data:
  vault_file:
  vault_logs:
  vault_ssh_manager_role:

networks:
  ansible_network:
    driver: bridge
